on: [push, pull_request]

env:
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "VS2019 x86 Release", os: windows-latest,
              env: { CONAN_VISUAL_VERSIONS: 16, CONAN_ARCHS: x86, CONAN_BUILD_TYPES: "Release" } }
          - { name: "VS2019 x86_64 Release", os: windows-latest,
              env: { CONAN_VISUAL_VERSIONS: 16, CONAN_ARCHS: x86_64, CONAN_BUILD_TYPES: "Release" } }
          - { name: "MinGW x86 Release", os: windows-latest,
              env: { MINGW_CONFIGURATIONS: "8@x86@dwarf2@posix", CONAN_BUILD_TYPES: "Release", CONAN_BUILD_REQUIRES: 'msys2_installer/latest@bincrafters/stable' } }
          - { name: "MinGW x86_64 Release", os: windows-latest,
              env: { MINGW_CONFIGURATIONS: "8@x86_64@seh@posix", CONAN_BUILD_TYPES: "Release", CONAN_BUILD_REQUIRES: 'msys2_installer/latest@bincrafters/stable' } }

    steps:
      - name: Disable autocrlf
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install Conan
        run: |
          conan-shared-scripts\install_conan.bat
      - name: build
        env: ${{ matrix.config.env }}
        run: |
          python conan-shared-scripts/build.py --shared --recipe-subdir 1.x.x openssl 1.1.1g
